### ISSUE TITLE
Please fix RSS feed ("feed.xml")

### ISSUE THREAD

**Issue by sokai** [JRMurr/JRMurr.github.io#12]
Hey @JRMurr  :)

Today I recognised my feed reader has some probs to get the RSS feed of your post from https://johns.codes/feed.xml (which seems the _officially_ one).

 The feed worked some time ago and now I get a 404 :(

Plz, can you fix it?. :)

KR

**Comment by JRMurr** [comment]
Thanks for calling this out! I just merged a big change to my blog yesterday and looks like this got lost in the upgrade. Will fix soon!

**Comment by JRMurr** [comment]
I should be fixed, let me know if you see any issues!
